// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bt.proto

package rtkaczyk.eris.service.bluetooth;

public final class BtMessages {
  private BtMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional fixed64 frm = 1;
    boolean hasFrm();
    long getFrm();
    
    // optional fixed64 to = 2;
    boolean hasTo();
    long getTo();
    
    // optional int32 limit = 3;
    boolean hasLimit();
    int getLimit();
    
    // optional int32 batch = 4;
    boolean hasBatch();
    int getBatch();
    
    // optional bool full = 5 [default = true];
    boolean hasFull();
    boolean getFull();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional fixed64 frm = 1;
    public static final int FRM_FIELD_NUMBER = 1;
    private long frm_;
    public boolean hasFrm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getFrm() {
      return frm_;
    }
    
    // optional fixed64 to = 2;
    public static final int TO_FIELD_NUMBER = 2;
    private long to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTo() {
      return to_;
    }
    
    // optional int32 limit = 3;
    public static final int LIMIT_FIELD_NUMBER = 3;
    private int limit_;
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLimit() {
      return limit_;
    }
    
    // optional int32 batch = 4;
    public static final int BATCH_FIELD_NUMBER = 4;
    private int batch_;
    public boolean hasBatch() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getBatch() {
      return batch_;
    }
    
    // optional bool full = 5 [default = true];
    public static final int FULL_FIELD_NUMBER = 5;
    private boolean full_;
    public boolean hasFull() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getFull() {
      return full_;
    }
    
    private void initFields() {
      frm_ = 0L;
      to_ = 0L;
      limit_ = 0;
      batch_ = 0;
      full_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, frm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, to_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, limit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, batch_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, full_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, frm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, to_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, limit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batch_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, full_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.bluetooth.BtMessages.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.bluetooth.BtMessages.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Request_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.bluetooth.BtMessages.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        frm_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        limit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        batch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        full_ = true;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Request.getDescriptor();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Request getDefaultInstanceForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Request.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Request build() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.bluetooth.BtMessages.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.bluetooth.BtMessages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Request buildPartial() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Request result = new rtkaczyk.eris.service.bluetooth.BtMessages.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frm_ = frm_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.limit_ = limit_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.batch_ = batch_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.full_ = full_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.bluetooth.BtMessages.Request) {
          return mergeFrom((rtkaczyk.eris.service.bluetooth.BtMessages.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.bluetooth.BtMessages.Request other) {
        if (other == rtkaczyk.eris.service.bluetooth.BtMessages.Request.getDefaultInstance()) return this;
        if (other.hasFrm()) {
          setFrm(other.getFrm());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasLimit()) {
          setLimit(other.getLimit());
        }
        if (other.hasBatch()) {
          setBatch(other.getBatch());
        }
        if (other.hasFull()) {
          setFull(other.getFull());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              frm_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              to_ = input.readFixed64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              limit_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              batch_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              full_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional fixed64 frm = 1;
      private long frm_ ;
      public boolean hasFrm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getFrm() {
        return frm_;
      }
      public Builder setFrm(long value) {
        bitField0_ |= 0x00000001;
        frm_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frm_ = 0L;
        onChanged();
        return this;
      }
      
      // optional fixed64 to = 2;
      private long to_ ;
      public boolean hasTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTo() {
        return to_;
      }
      public Builder setTo(long value) {
        bitField0_ |= 0x00000002;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 limit = 3;
      private int limit_ ;
      public boolean hasLimit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLimit() {
        return limit_;
      }
      public Builder setLimit(int value) {
        bitField0_ |= 0x00000004;
        limit_ = value;
        onChanged();
        return this;
      }
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        limit_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 batch = 4;
      private int batch_ ;
      public boolean hasBatch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getBatch() {
        return batch_;
      }
      public Builder setBatch(int value) {
        bitField0_ |= 0x00000008;
        batch_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batch_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool full = 5 [default = true];
      private boolean full_ = true;
      public boolean hasFull() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getFull() {
        return full_;
      }
      public Builder setFull(boolean value) {
        bitField0_ |= 0x00000010;
        full_ = value;
        onChanged();
        return this;
      }
      public Builder clearFull() {
        bitField0_ = (bitField0_ & ~0x00000010);
        full_ = true;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.bluetooth.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.bluetooth.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional fixed64 frm = 1;
    boolean hasFrm();
    long getFrm();
    
    // optional fixed64 to = 2;
    boolean hasTo();
    long getTo();
    
    // repeated .rtkaczyk.eris.service.bluetooth.Packet packets = 3;
    java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet> 
        getPacketsList();
    rtkaczyk.eris.service.bluetooth.BtMessages.Packet getPackets(int index);
    int getPacketsCount();
    java.util.List<? extends rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder> 
        getPacketsOrBuilderList();
    rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder getPacketsOrBuilder(
        int index);
    
    // optional int32 noPackets = 4;
    boolean hasNoPackets();
    int getNoPackets();
    
    // optional .rtkaczyk.eris.service.bluetooth.Error error = 5;
    boolean hasError();
    rtkaczyk.eris.service.bluetooth.BtMessages.Error getError();
    rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder getErrorOrBuilder();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional fixed64 frm = 1;
    public static final int FRM_FIELD_NUMBER = 1;
    private long frm_;
    public boolean hasFrm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getFrm() {
      return frm_;
    }
    
    // optional fixed64 to = 2;
    public static final int TO_FIELD_NUMBER = 2;
    private long to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTo() {
      return to_;
    }
    
    // repeated .rtkaczyk.eris.service.bluetooth.Packet packets = 3;
    public static final int PACKETS_FIELD_NUMBER = 3;
    private java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet> packets_;
    public java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet> getPacketsList() {
      return packets_;
    }
    public java.util.List<? extends rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder> 
        getPacketsOrBuilderList() {
      return packets_;
    }
    public int getPacketsCount() {
      return packets_.size();
    }
    public rtkaczyk.eris.service.bluetooth.BtMessages.Packet getPackets(int index) {
      return packets_.get(index);
    }
    public rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder getPacketsOrBuilder(
        int index) {
      return packets_.get(index);
    }
    
    // optional int32 noPackets = 4;
    public static final int NOPACKETS_FIELD_NUMBER = 4;
    private int noPackets_;
    public boolean hasNoPackets() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNoPackets() {
      return noPackets_;
    }
    
    // optional .rtkaczyk.eris.service.bluetooth.Error error = 5;
    public static final int ERROR_FIELD_NUMBER = 5;
    private rtkaczyk.eris.service.bluetooth.BtMessages.Error error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public rtkaczyk.eris.service.bluetooth.BtMessages.Error getError() {
      return error_;
    }
    public rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder getErrorOrBuilder() {
      return error_;
    }
    
    private void initFields() {
      frm_ = 0L;
      to_ = 0L;
      packets_ = java.util.Collections.emptyList();
      noPackets_ = 0;
      error_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPacketsCount(); i++) {
        if (!getPackets(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasError()) {
        if (!getError().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, frm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, to_);
      }
      for (int i = 0; i < packets_.size(); i++) {
        output.writeMessage(3, packets_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, noPackets_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, error_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, frm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, to_);
      }
      for (int i = 0; i < packets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, packets_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, noPackets_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.bluetooth.BtMessages.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.bluetooth.BtMessages.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Response_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.bluetooth.BtMessages.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPacketsFieldBuilder();
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        frm_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (packetsBuilder_ == null) {
          packets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          packetsBuilder_.clear();
        }
        noPackets_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (errorBuilder_ == null) {
          error_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Response.getDescriptor();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Response getDefaultInstanceForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Response.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Response build() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.bluetooth.BtMessages.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.bluetooth.BtMessages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Response buildPartial() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Response result = new rtkaczyk.eris.service.bluetooth.BtMessages.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frm_ = frm_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.to_ = to_;
        if (packetsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            packets_ = java.util.Collections.unmodifiableList(packets_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.packets_ = packets_;
        } else {
          result.packets_ = packetsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.noPackets_ = noPackets_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.bluetooth.BtMessages.Response) {
          return mergeFrom((rtkaczyk.eris.service.bluetooth.BtMessages.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.bluetooth.BtMessages.Response other) {
        if (other == rtkaczyk.eris.service.bluetooth.BtMessages.Response.getDefaultInstance()) return this;
        if (other.hasFrm()) {
          setFrm(other.getFrm());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (packetsBuilder_ == null) {
          if (!other.packets_.isEmpty()) {
            if (packets_.isEmpty()) {
              packets_ = other.packets_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePacketsIsMutable();
              packets_.addAll(other.packets_);
            }
            onChanged();
          }
        } else {
          if (!other.packets_.isEmpty()) {
            if (packetsBuilder_.isEmpty()) {
              packetsBuilder_.dispose();
              packetsBuilder_ = null;
              packets_ = other.packets_;
              bitField0_ = (bitField0_ & ~0x00000004);
              packetsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPacketsFieldBuilder() : null;
            } else {
              packetsBuilder_.addAllMessages(other.packets_);
            }
          }
        }
        if (other.hasNoPackets()) {
          setNoPackets(other.getNoPackets());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPacketsCount(); i++) {
          if (!getPackets(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasError()) {
          if (!getError().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              frm_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              to_ = input.readFixed64();
              break;
            }
            case 26: {
              rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder subBuilder = rtkaczyk.eris.service.bluetooth.BtMessages.Packet.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPackets(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              noPackets_ = input.readInt32();
              break;
            }
            case 42: {
              rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder subBuilder = rtkaczyk.eris.service.bluetooth.BtMessages.Error.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional fixed64 frm = 1;
      private long frm_ ;
      public boolean hasFrm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getFrm() {
        return frm_;
      }
      public Builder setFrm(long value) {
        bitField0_ |= 0x00000001;
        frm_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frm_ = 0L;
        onChanged();
        return this;
      }
      
      // optional fixed64 to = 2;
      private long to_ ;
      public boolean hasTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTo() {
        return to_;
      }
      public Builder setTo(long value) {
        bitField0_ |= 0x00000002;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .rtkaczyk.eris.service.bluetooth.Packet packets = 3;
      private java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet> packets_ =
        java.util.Collections.emptyList();
      private void ensurePacketsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          packets_ = new java.util.ArrayList<rtkaczyk.eris.service.bluetooth.BtMessages.Packet>(packets_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rtkaczyk.eris.service.bluetooth.BtMessages.Packet, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder> packetsBuilder_;
      
      public java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet> getPacketsList() {
        if (packetsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packets_);
        } else {
          return packetsBuilder_.getMessageList();
        }
      }
      public int getPacketsCount() {
        if (packetsBuilder_ == null) {
          return packets_.size();
        } else {
          return packetsBuilder_.getCount();
        }
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet getPackets(int index) {
        if (packetsBuilder_ == null) {
          return packets_.get(index);
        } else {
          return packetsBuilder_.getMessage(index);
        }
      }
      public Builder setPackets(
          int index, rtkaczyk.eris.service.bluetooth.BtMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.set(index, value);
          onChanged();
        } else {
          packetsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPackets(
          int index, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.set(index, builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPackets(rtkaczyk.eris.service.bluetooth.BtMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.add(value);
          onChanged();
        } else {
          packetsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPackets(
          int index, rtkaczyk.eris.service.bluetooth.BtMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.add(index, value);
          onChanged();
        } else {
          packetsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPackets(
          rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.add(builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPackets(
          int index, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.add(index, builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPackets(
          java.lang.Iterable<? extends rtkaczyk.eris.service.bluetooth.BtMessages.Packet> values) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          super.addAll(values, packets_);
          onChanged();
        } else {
          packetsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPackets() {
        if (packetsBuilder_ == null) {
          packets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          packetsBuilder_.clear();
        }
        return this;
      }
      public Builder removePackets(int index) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.remove(index);
          onChanged();
        } else {
          packetsBuilder_.remove(index);
        }
        return this;
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder getPacketsBuilder(
          int index) {
        return getPacketsFieldBuilder().getBuilder(index);
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder getPacketsOrBuilder(
          int index) {
        if (packetsBuilder_ == null) {
          return packets_.get(index);  } else {
          return packetsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder> 
           getPacketsOrBuilderList() {
        if (packetsBuilder_ != null) {
          return packetsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packets_);
        }
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder addPacketsBuilder() {
        return getPacketsFieldBuilder().addBuilder(
            rtkaczyk.eris.service.bluetooth.BtMessages.Packet.getDefaultInstance());
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder addPacketsBuilder(
          int index) {
        return getPacketsFieldBuilder().addBuilder(
            index, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.getDefaultInstance());
      }
      public java.util.List<rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder> 
           getPacketsBuilderList() {
        return getPacketsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rtkaczyk.eris.service.bluetooth.BtMessages.Packet, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder> 
          getPacketsFieldBuilder() {
        if (packetsBuilder_ == null) {
          packetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rtkaczyk.eris.service.bluetooth.BtMessages.Packet, rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder>(
                  packets_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          packets_ = null;
        }
        return packetsBuilder_;
      }
      
      // optional int32 noPackets = 4;
      private int noPackets_ ;
      public boolean hasNoPackets() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getNoPackets() {
        return noPackets_;
      }
      public Builder setNoPackets(int value) {
        bitField0_ |= 0x00000008;
        noPackets_ = value;
        onChanged();
        return this;
      }
      public Builder clearNoPackets() {
        bitField0_ = (bitField0_ & ~0x00000008);
        noPackets_ = 0;
        onChanged();
        return this;
      }
      
      // optional .rtkaczyk.eris.service.bluetooth.Error error = 5;
      private rtkaczyk.eris.service.bluetooth.BtMessages.Error error_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rtkaczyk.eris.service.bluetooth.BtMessages.Error, rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder> errorBuilder_;
      public boolean hasError() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      public Builder setError(rtkaczyk.eris.service.bluetooth.BtMessages.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setError(
          rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeError(rtkaczyk.eris.service.bluetooth.BtMessages.Error value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              error_ != rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance()) {
            error_ =
              rtkaczyk.eris.service.bluetooth.BtMessages.Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder getErrorBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rtkaczyk.eris.service.bluetooth.BtMessages.Error, rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rtkaczyk.eris.service.bluetooth.BtMessages.Error, rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder, rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder>(
                  error_,
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.bluetooth.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.bluetooth.Response)
  }
  
  public interface PacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional fixed64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required bytes data = 2;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage
      implements PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(Builder builder) {
      super(builder);
    }
    private Packet(boolean noInit) {}
    
    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }
    
    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Packet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Packet_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional fixed64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      timestamp_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.bluetooth.BtMessages.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.bluetooth.BtMessages.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Packet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Packet_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.bluetooth.BtMessages.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Packet.getDescriptor();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet getDefaultInstanceForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Packet.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet build() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.bluetooth.BtMessages.Packet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.bluetooth.BtMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Packet buildPartial() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Packet result = new rtkaczyk.eris.service.bluetooth.BtMessages.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.bluetooth.BtMessages.Packet) {
          return mergeFrom((rtkaczyk.eris.service.bluetooth.BtMessages.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.bluetooth.BtMessages.Packet other) {
        if (other == rtkaczyk.eris.service.bluetooth.BtMessages.Packet.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readFixed64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional fixed64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.bluetooth.Packet)
    }
    
    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.bluetooth.Packet)
  }
  
  public interface ErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rtkaczyk.eris.service.bluetooth.Error.Code code = 1;
    boolean hasCode();
    rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code getCode();
    
    // optional string description = 2;
    boolean hasDescription();
    String getDescription();
  }
  public static final class Error extends
      com.google.protobuf.GeneratedMessage
      implements ErrorOrBuilder {
    // Use Error.newBuilder() to construct.
    private Error(Builder builder) {
      super(builder);
    }
    private Error(boolean noInit) {}
    
    private static final Error defaultInstance;
    public static Error getDefaultInstance() {
      return defaultInstance;
    }
    
    public Error getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Error_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Error_fieldAccessorTable;
    }
    
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      CONNECTION_ERROR(0, 0),
      INVALID_REQUEST(1, 1),
      INTERNAL_ERROR(2, 2),
      ;
      
      public static final int CONNECTION_ERROR_VALUE = 0;
      public static final int INVALID_REQUEST_VALUE = 1;
      public static final int INTERNAL_ERROR_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Code valueOf(int value) {
        switch (value) {
          case 0: return CONNECTION_ERROR;
          case 1: return INVALID_REQUEST;
          case 2: return INTERNAL_ERROR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Code[] VALUES = {
        CONNECTION_ERROR, INVALID_REQUEST, INTERNAL_ERROR, 
      };
      
      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:rtkaczyk.eris.service.bluetooth.Error.Code)
    }
    
    private int bitField0_;
    // required .rtkaczyk.eris.service.bluetooth.Error.Code code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code getCode() {
      return code_;
    }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      code_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code.CONNECTION_ERROR;
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.bluetooth.BtMessages.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.bluetooth.BtMessages.Error prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.bluetooth.BtMessages.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Error_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.internal_static_rtkaczyk_eris_service_bluetooth_Error_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.bluetooth.BtMessages.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code.CONNECTION_ERROR;
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDescriptor();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error getDefaultInstanceForType() {
        return rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error build() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.bluetooth.BtMessages.Error buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.bluetooth.BtMessages.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error buildPartial() {
        rtkaczyk.eris.service.bluetooth.BtMessages.Error result = new rtkaczyk.eris.service.bluetooth.BtMessages.Error(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.bluetooth.BtMessages.Error) {
          return mergeFrom((rtkaczyk.eris.service.bluetooth.BtMessages.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.bluetooth.BtMessages.Error other) {
        if (other == rtkaczyk.eris.service.bluetooth.BtMessages.Error.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code value = rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rtkaczyk.eris.service.bluetooth.Error.Code code = 1;
      private rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code code_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code.CONNECTION_ERROR;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code getCode() {
        return code_;
      }
      public Builder setCode(rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = rtkaczyk.eris.service.bluetooth.BtMessages.Error.Code.CONNECTION_ERROR;
        onChanged();
        return this;
      }
      
      // optional string description = 2;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.bluetooth.Error)
    }
    
    static {
      defaultInstance = new Error(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.bluetooth.Error)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_bluetooth_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_bluetooth_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_bluetooth_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_bluetooth_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_bluetooth_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_bluetooth_Packet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_bluetooth_Error_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_bluetooth_Error_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010bt.proto\022\037rtkaczyk.eris.service.blueto" +
      "oth\"T\n\007Request\022\013\n\003frm\030\001 \001(\006\022\n\n\002to\030\002 \001(\006\022" +
      "\r\n\005limit\030\003 \001(\005\022\r\n\005batch\030\004 \001(\005\022\022\n\004full\030\005 " +
      "\001(\010:\004true\"\247\001\n\010Response\022\013\n\003frm\030\001 \001(\006\022\n\n\002t" +
      "o\030\002 \001(\006\0228\n\007packets\030\003 \003(\0132\'.rtkaczyk.eris" +
      ".service.bluetooth.Packet\022\021\n\tnoPackets\030\004" +
      " \001(\005\0225\n\005error\030\005 \001(\0132&.rtkaczyk.eris.serv" +
      "ice.bluetooth.Error\")\n\006Packet\022\021\n\ttimesta" +
      "mp\030\001 \001(\006\022\014\n\004data\030\002 \002(\014\"\236\001\n\005Error\0229\n\004code" +
      "\030\001 \002(\0162+.rtkaczyk.eris.service.bluetooth",
      ".Error.Code\022\023\n\013description\030\002 \001(\t\"E\n\004Code" +
      "\022\024\n\020CONNECTION_ERROR\020\000\022\023\n\017INVALID_REQUES" +
      "T\020\001\022\022\n\016INTERNAL_ERROR\020\002B\014B\nBtMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rtkaczyk_eris_service_bluetooth_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rtkaczyk_eris_service_bluetooth_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_bluetooth_Request_descriptor,
              new java.lang.String[] { "Frm", "To", "Limit", "Batch", "Full", },
              rtkaczyk.eris.service.bluetooth.BtMessages.Request.class,
              rtkaczyk.eris.service.bluetooth.BtMessages.Request.Builder.class);
          internal_static_rtkaczyk_eris_service_bluetooth_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rtkaczyk_eris_service_bluetooth_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_bluetooth_Response_descriptor,
              new java.lang.String[] { "Frm", "To", "Packets", "NoPackets", "Error", },
              rtkaczyk.eris.service.bluetooth.BtMessages.Response.class,
              rtkaczyk.eris.service.bluetooth.BtMessages.Response.Builder.class);
          internal_static_rtkaczyk_eris_service_bluetooth_Packet_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rtkaczyk_eris_service_bluetooth_Packet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_bluetooth_Packet_descriptor,
              new java.lang.String[] { "Timestamp", "Data", },
              rtkaczyk.eris.service.bluetooth.BtMessages.Packet.class,
              rtkaczyk.eris.service.bluetooth.BtMessages.Packet.Builder.class);
          internal_static_rtkaczyk_eris_service_bluetooth_Error_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_rtkaczyk_eris_service_bluetooth_Error_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_bluetooth_Error_descriptor,
              new java.lang.String[] { "Code", "Description", },
              rtkaczyk.eris.service.bluetooth.BtMessages.Error.class,
              rtkaczyk.eris.service.bluetooth.BtMessages.Error.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
