// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fwd.proto

package rtkaczyk.eris.service.forwarding;

public final class FwdMessages {
  private FwdMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rtkaczyk.eris.service.forwarding.Packet packets = 1;
    java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet> 
        getPacketsList();
    rtkaczyk.eris.service.forwarding.FwdMessages.Packet getPackets(int index);
    int getPacketsCount();
    java.util.List<? extends rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder> 
        getPacketsOrBuilderList();
    rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder getPacketsOrBuilder(
        int index);
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Request_fieldAccessorTable;
    }
    
    // repeated .rtkaczyk.eris.service.forwarding.Packet packets = 1;
    public static final int PACKETS_FIELD_NUMBER = 1;
    private java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet> packets_;
    public java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet> getPacketsList() {
      return packets_;
    }
    public java.util.List<? extends rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder> 
        getPacketsOrBuilderList() {
      return packets_;
    }
    public int getPacketsCount() {
      return packets_.size();
    }
    public rtkaczyk.eris.service.forwarding.FwdMessages.Packet getPackets(int index) {
      return packets_.get(index);
    }
    public rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder getPacketsOrBuilder(
        int index) {
      return packets_.get(index);
    }
    
    private void initFields() {
      packets_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPacketsCount(); i++) {
        if (!getPackets(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < packets_.size(); i++) {
        output.writeMessage(1, packets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < packets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packets_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.forwarding.FwdMessages.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.forwarding.FwdMessages.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Request_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.forwarding.FwdMessages.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPacketsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (packetsBuilder_ == null) {
          packets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          packetsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Request.getDescriptor();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Request getDefaultInstanceForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Request.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Request build() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.forwarding.FwdMessages.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.forwarding.FwdMessages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Request buildPartial() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Request result = new rtkaczyk.eris.service.forwarding.FwdMessages.Request(this);
        int from_bitField0_ = bitField0_;
        if (packetsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            packets_ = java.util.Collections.unmodifiableList(packets_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packets_ = packets_;
        } else {
          result.packets_ = packetsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.forwarding.FwdMessages.Request) {
          return mergeFrom((rtkaczyk.eris.service.forwarding.FwdMessages.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.forwarding.FwdMessages.Request other) {
        if (other == rtkaczyk.eris.service.forwarding.FwdMessages.Request.getDefaultInstance()) return this;
        if (packetsBuilder_ == null) {
          if (!other.packets_.isEmpty()) {
            if (packets_.isEmpty()) {
              packets_ = other.packets_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePacketsIsMutable();
              packets_.addAll(other.packets_);
            }
            onChanged();
          }
        } else {
          if (!other.packets_.isEmpty()) {
            if (packetsBuilder_.isEmpty()) {
              packetsBuilder_.dispose();
              packetsBuilder_ = null;
              packets_ = other.packets_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packetsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPacketsFieldBuilder() : null;
            } else {
              packetsBuilder_.addAllMessages(other.packets_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPacketsCount(); i++) {
          if (!getPackets(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder subBuilder = rtkaczyk.eris.service.forwarding.FwdMessages.Packet.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPackets(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rtkaczyk.eris.service.forwarding.Packet packets = 1;
      private java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet> packets_ =
        java.util.Collections.emptyList();
      private void ensurePacketsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          packets_ = new java.util.ArrayList<rtkaczyk.eris.service.forwarding.FwdMessages.Packet>(packets_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rtkaczyk.eris.service.forwarding.FwdMessages.Packet, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder> packetsBuilder_;
      
      public java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet> getPacketsList() {
        if (packetsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packets_);
        } else {
          return packetsBuilder_.getMessageList();
        }
      }
      public int getPacketsCount() {
        if (packetsBuilder_ == null) {
          return packets_.size();
        } else {
          return packetsBuilder_.getCount();
        }
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet getPackets(int index) {
        if (packetsBuilder_ == null) {
          return packets_.get(index);
        } else {
          return packetsBuilder_.getMessage(index);
        }
      }
      public Builder setPackets(
          int index, rtkaczyk.eris.service.forwarding.FwdMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.set(index, value);
          onChanged();
        } else {
          packetsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPackets(
          int index, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.set(index, builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPackets(rtkaczyk.eris.service.forwarding.FwdMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.add(value);
          onChanged();
        } else {
          packetsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPackets(
          int index, rtkaczyk.eris.service.forwarding.FwdMessages.Packet value) {
        if (packetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketsIsMutable();
          packets_.add(index, value);
          onChanged();
        } else {
          packetsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPackets(
          rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.add(builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPackets(
          int index, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder builderForValue) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.add(index, builderForValue.build());
          onChanged();
        } else {
          packetsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPackets(
          java.lang.Iterable<? extends rtkaczyk.eris.service.forwarding.FwdMessages.Packet> values) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          super.addAll(values, packets_);
          onChanged();
        } else {
          packetsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPackets() {
        if (packetsBuilder_ == null) {
          packets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packetsBuilder_.clear();
        }
        return this;
      }
      public Builder removePackets(int index) {
        if (packetsBuilder_ == null) {
          ensurePacketsIsMutable();
          packets_.remove(index);
          onChanged();
        } else {
          packetsBuilder_.remove(index);
        }
        return this;
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder getPacketsBuilder(
          int index) {
        return getPacketsFieldBuilder().getBuilder(index);
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder getPacketsOrBuilder(
          int index) {
        if (packetsBuilder_ == null) {
          return packets_.get(index);  } else {
          return packetsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder> 
           getPacketsOrBuilderList() {
        if (packetsBuilder_ != null) {
          return packetsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packets_);
        }
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder addPacketsBuilder() {
        return getPacketsFieldBuilder().addBuilder(
            rtkaczyk.eris.service.forwarding.FwdMessages.Packet.getDefaultInstance());
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder addPacketsBuilder(
          int index) {
        return getPacketsFieldBuilder().addBuilder(
            index, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.getDefaultInstance());
      }
      public java.util.List<rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder> 
           getPacketsBuilderList() {
        return getPacketsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rtkaczyk.eris.service.forwarding.FwdMessages.Packet, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder> 
          getPacketsFieldBuilder() {
        if (packetsBuilder_ == null) {
          packetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rtkaczyk.eris.service.forwarding.FwdMessages.Packet, rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder>(
                  packets_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          packets_ = null;
        }
        return packetsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.forwarding.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.forwarding.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .rtkaczyk.eris.service.forwarding.Error error = 1;
    boolean hasError();
    rtkaczyk.eris.service.forwarding.FwdMessages.Error getError();
    rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder getErrorOrBuilder();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .rtkaczyk.eris.service.forwarding.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private rtkaczyk.eris.service.forwarding.FwdMessages.Error error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rtkaczyk.eris.service.forwarding.FwdMessages.Error getError() {
      return error_;
    }
    public rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder getErrorOrBuilder() {
      return error_;
    }
    
    private void initFields() {
      error_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasError()) {
        if (!getError().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, error_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.forwarding.FwdMessages.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.forwarding.FwdMessages.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Response_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.forwarding.FwdMessages.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (errorBuilder_ == null) {
          error_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Response.getDescriptor();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Response getDefaultInstanceForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Response.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Response build() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.forwarding.FwdMessages.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.forwarding.FwdMessages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Response buildPartial() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Response result = new rtkaczyk.eris.service.forwarding.FwdMessages.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.forwarding.FwdMessages.Response) {
          return mergeFrom((rtkaczyk.eris.service.forwarding.FwdMessages.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.forwarding.FwdMessages.Response other) {
        if (other == rtkaczyk.eris.service.forwarding.FwdMessages.Response.getDefaultInstance()) return this;
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasError()) {
          if (!getError().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder subBuilder = rtkaczyk.eris.service.forwarding.FwdMessages.Error.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .rtkaczyk.eris.service.forwarding.Error error = 1;
      private rtkaczyk.eris.service.forwarding.FwdMessages.Error error_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rtkaczyk.eris.service.forwarding.FwdMessages.Error, rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder> errorBuilder_;
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      public Builder setError(rtkaczyk.eris.service.forwarding.FwdMessages.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setError(
          rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeError(rtkaczyk.eris.service.forwarding.FwdMessages.Error value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              error_ != rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance()) {
            error_ =
              rtkaczyk.eris.service.forwarding.FwdMessages.Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder getErrorBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rtkaczyk.eris.service.forwarding.FwdMessages.Error, rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rtkaczyk.eris.service.forwarding.FwdMessages.Error, rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder, rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder>(
                  error_,
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.forwarding.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.forwarding.Response)
  }
  
  public interface PacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string device = 1;
    boolean hasDevice();
    String getDevice();
    
    // optional fixed64 timestamp = 2;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required bytes data = 3;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage
      implements PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(Builder builder) {
      super(builder);
    }
    private Packet(boolean noInit) {}
    
    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }
    
    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Packet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Packet_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string device = 1;
    public static final int DEVICE_FIELD_NUMBER = 1;
    private java.lang.Object device_;
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDevice() {
      java.lang.Object ref = device_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          device_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional fixed64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      device_ = "";
      timestamp_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDevice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.forwarding.FwdMessages.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.forwarding.FwdMessages.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Packet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Packet_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.forwarding.FwdMessages.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        device_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Packet.getDescriptor();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet getDefaultInstanceForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Packet.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet build() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.forwarding.FwdMessages.Packet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.forwarding.FwdMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Packet buildPartial() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Packet result = new rtkaczyk.eris.service.forwarding.FwdMessages.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.device_ = device_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.forwarding.FwdMessages.Packet) {
          return mergeFrom((rtkaczyk.eris.service.forwarding.FwdMessages.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.forwarding.FwdMessages.Packet other) {
        if (other == rtkaczyk.eris.service.forwarding.FwdMessages.Packet.getDefaultInstance()) return this;
        if (other.hasDevice()) {
          setDevice(other.getDevice());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDevice()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              device_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readFixed64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string device = 1;
      private java.lang.Object device_ = "";
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDevice() {
        java.lang.Object ref = device_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          device_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDevice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        device_ = value;
        onChanged();
        return this;
      }
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        device_ = getDefaultInstance().getDevice();
        onChanged();
        return this;
      }
      void setDevice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        device_ = value;
        onChanged();
      }
      
      // optional fixed64 timestamp = 2;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.forwarding.Packet)
    }
    
    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.forwarding.Packet)
  }
  
  public interface ErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rtkaczyk.eris.service.forwarding.Error.Code code = 1;
    boolean hasCode();
    rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code getCode();
    
    // optional string description = 2;
    boolean hasDescription();
    String getDescription();
  }
  public static final class Error extends
      com.google.protobuf.GeneratedMessage
      implements ErrorOrBuilder {
    // Use Error.newBuilder() to construct.
    private Error(Builder builder) {
      super(builder);
    }
    private Error(boolean noInit) {}
    
    private static final Error defaultInstance;
    public static Error getDefaultInstance() {
      return defaultInstance;
    }
    
    public Error getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Error_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Error_fieldAccessorTable;
    }
    
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      CONNECTION_ERROR(0, 0),
      INVALID_REQUEST(1, 1),
      INTERNAL_ERROR(2, 2),
      ;
      
      public static final int CONNECTION_ERROR_VALUE = 0;
      public static final int INVALID_REQUEST_VALUE = 1;
      public static final int INTERNAL_ERROR_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Code valueOf(int value) {
        switch (value) {
          case 0: return CONNECTION_ERROR;
          case 1: return INVALID_REQUEST;
          case 2: return INTERNAL_ERROR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Code[] VALUES = {
        CONNECTION_ERROR, INVALID_REQUEST, INTERNAL_ERROR, 
      };
      
      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:rtkaczyk.eris.service.forwarding.Error.Code)
    }
    
    private int bitField0_;
    // required .rtkaczyk.eris.service.forwarding.Error.Code code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code getCode() {
      return code_;
    }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      code_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code.CONNECTION_ERROR;
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rtkaczyk.eris.service.forwarding.FwdMessages.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rtkaczyk.eris.service.forwarding.FwdMessages.Error prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rtkaczyk.eris.service.forwarding.FwdMessages.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Error_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.internal_static_rtkaczyk_eris_service_forwarding_Error_fieldAccessorTable;
      }
      
      // Construct using rtkaczyk.eris.service.forwarding.FwdMessages.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code.CONNECTION_ERROR;
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDescriptor();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error getDefaultInstanceForType() {
        return rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance();
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error build() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rtkaczyk.eris.service.forwarding.FwdMessages.Error buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rtkaczyk.eris.service.forwarding.FwdMessages.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error buildPartial() {
        rtkaczyk.eris.service.forwarding.FwdMessages.Error result = new rtkaczyk.eris.service.forwarding.FwdMessages.Error(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rtkaczyk.eris.service.forwarding.FwdMessages.Error) {
          return mergeFrom((rtkaczyk.eris.service.forwarding.FwdMessages.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rtkaczyk.eris.service.forwarding.FwdMessages.Error other) {
        if (other == rtkaczyk.eris.service.forwarding.FwdMessages.Error.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code value = rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rtkaczyk.eris.service.forwarding.Error.Code code = 1;
      private rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code code_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code.CONNECTION_ERROR;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code getCode() {
        return code_;
      }
      public Builder setCode(rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = rtkaczyk.eris.service.forwarding.FwdMessages.Error.Code.CONNECTION_ERROR;
        onChanged();
        return this;
      }
      
      // optional string description = 2;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rtkaczyk.eris.service.forwarding.Error)
    }
    
    static {
      defaultInstance = new Error(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rtkaczyk.eris.service.forwarding.Error)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_forwarding_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_forwarding_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_forwarding_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_forwarding_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_forwarding_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_forwarding_Packet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rtkaczyk_eris_service_forwarding_Error_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtkaczyk_eris_service_forwarding_Error_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfwd.proto\022 rtkaczyk.eris.service.forwa" +
      "rding\"D\n\007Request\0229\n\007packets\030\001 \003(\0132(.rtka" +
      "czyk.eris.service.forwarding.Packet\"B\n\010R" +
      "esponse\0226\n\005error\030\001 \001(\0132\'.rtkaczyk.eris.s" +
      "ervice.forwarding.Error\"9\n\006Packet\022\016\n\006dev" +
      "ice\030\001 \002(\t\022\021\n\ttimestamp\030\002 \001(\006\022\014\n\004data\030\003 \002" +
      "(\014\"\237\001\n\005Error\022:\n\004code\030\001 \002(\0162,.rtkaczyk.er" +
      "is.service.forwarding.Error.Code\022\023\n\013desc" +
      "ription\030\002 \001(\t\"E\n\004Code\022\024\n\020CONNECTION_ERRO" +
      "R\020\000\022\023\n\017INVALID_REQUEST\020\001\022\022\n\016INTERNAL_ERR",
      "OR\020\002B\rB\013FwdMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rtkaczyk_eris_service_forwarding_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rtkaczyk_eris_service_forwarding_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_forwarding_Request_descriptor,
              new java.lang.String[] { "Packets", },
              rtkaczyk.eris.service.forwarding.FwdMessages.Request.class,
              rtkaczyk.eris.service.forwarding.FwdMessages.Request.Builder.class);
          internal_static_rtkaczyk_eris_service_forwarding_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rtkaczyk_eris_service_forwarding_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_forwarding_Response_descriptor,
              new java.lang.String[] { "Error", },
              rtkaczyk.eris.service.forwarding.FwdMessages.Response.class,
              rtkaczyk.eris.service.forwarding.FwdMessages.Response.Builder.class);
          internal_static_rtkaczyk_eris_service_forwarding_Packet_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rtkaczyk_eris_service_forwarding_Packet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_forwarding_Packet_descriptor,
              new java.lang.String[] { "Device", "Timestamp", "Data", },
              rtkaczyk.eris.service.forwarding.FwdMessages.Packet.class,
              rtkaczyk.eris.service.forwarding.FwdMessages.Packet.Builder.class);
          internal_static_rtkaczyk_eris_service_forwarding_Error_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_rtkaczyk_eris_service_forwarding_Error_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rtkaczyk_eris_service_forwarding_Error_descriptor,
              new java.lang.String[] { "Code", "Description", },
              rtkaczyk.eris.service.forwarding.FwdMessages.Error.class,
              rtkaczyk.eris.service.forwarding.FwdMessages.Error.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
